# Spring Boot configuration
spring:
  profiles:
    active: development
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
    static-path-pattern: /resources/**
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:captcha
    username: sa
    password:
    driver-class-name: org.h2.Driver

    # JPA properties - postgresSql
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true